name: econ
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10  # Updated to a more recent version
  - pytorch=2.0
  - torchvision
  - torchaudio
  - cudatoolkit=11.8  # Keeping CUDA to 11.8 for compatibility
  - pytorch-cuda=11.8
  - fvcore
  - iopath
  - pyembree
  - cupy
  - cython
  - pip