name: econ
# Path where the model's checkpoint files (pre-trained models) are stored.
ckpt_dir: "./data/ckpt/"
# Path to the checkpoint file for the normal map prediction model.
normal_path: "./data/ckpt/normal.ckpt"
# Path to the checkpoint file for the IF-Net model (used for shape completion).
ifnet_path: "./data/ckpt/ifnet.ckpt"
# Path where the results (output meshes, normal maps, etc.) will be saved.
results_path: "./results"

net:
  in_nml: (('image',3), ('T_normal_F',3), ('T_normal_B',3))
  in_geo: (('normal_F',3), ('normal_B',3))

test_mode: True
batch_size: 1

dataset:
  prior_type: "SMPL"

vol_res: 256
mcube_res: 256
clean_mesh: True
cloth_overlap_thres: 0.50
body_overlap_thres: 0.00
force_smpl_optim: True


# normal_model could be '1b' if CUDA OOM, see apps/sapiens.py

sapiens:
  use: True
  seg_model: "fg-bg-1b"
  normal_model: "2b" 

# For crowded / occluded scene
# body_overlap_thres: 0.98

bni:
  k: 4
  lambda1: 1e-4
  boundary_consist: 1e-6
  poisson_depth: 10
  use_smpl: ["hand"]
  use_ifnet: False
  use_poisson: True
  hand_thres: 8e-2
  face_thres: 6e-2
  thickness: 0.02
  hps_type: "pixie"
  texture_src: "image"
  cut_intersection: True
